- name: Install Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven_setup

- name: check if the user "roboshop" exists or not , if not create a user
  ansible.builtin.command: id roboshop
  register: output
  ignore_errors: true

- name:  print the output
  ansible.builtin.debug:
    msg: "output is : {{output.rc}}"

- name:  check the exit status , if not equals to 0 , create a user
  ansible.builtin.user:
    name: "roboshop" 
  when: output.rc !=0

- name: check if the /app directory exists, if not create one
  ansible.builtin.stat:
    path: /app
  register: output

- name: print the exit status
  ansible.builtin.debug:
    msg: "{{output}}"
  
- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory
  when: output.stat.exists == false

- name: Download the application code to created app directory
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
    dest: /tmp

- name: Extract the Catalouge artifact in /app
  ansible.builtin.unarchive:
    src: /tmp/shipping.zip
    dest: /app
    remote_src: yes # means catalouge.zip already available in catalouge server otherise it checks dor the catalouge.zip in the ansible server

- name: Install the application dependencies
  ansible.builtin.command: mvn clean package
  #we have to change the directory to /app
  args:
    chdir: /app    

- name: rename the jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  #we have to change the directory to /app
  args:
    chdir: /app

- name: creating systemd service
  ansible.builtin.copy:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: daemon load the service 
  ansible.builtin.systemd:
    daemon_reload: true

- name: start and enable the Service
  ansible.builtin.service:
    name: shipping
    enabled: yes 
    state: started

- name: install mysql
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql.devopsvani.online -uroot -pRoboShop@1 < /app/schema/shipping.sql

- name: restart the service
  ansible.builtin.service:
    name: shipping
    state: restarted     