- name: Install Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven_setup

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup   

- name: Install the application dependencies
  ansible.builtin.command: mvn clean package
  #we have to change the directory to /app
  args:
    chdir: /app    

- name: rename the jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  #we have to change the directory to /app
  args:
    chdir: /app

- name: load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql_schema

- name: Seup systemd service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup 

