- name: Install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python_setup

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup   


- name: Lets download the dependencies.
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Seup systemd service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup 
  