- name: restart nginx #name should be same as we gave while using notify keyword , when it sees notify keyword , it searches for handler directory 
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes