- name: So lets disable MySQL 8 version.
  ansible.builtin.shell: yum module disable mysql -y 

- name: setting the mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed 

- name:  enable and start the service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started  

- name: We need to change the default root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1