- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Start & Enable Nginx service 
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

  # method1: remove the html directory and create it again
- name: Remove the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download the frontend content  
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: Extract the front end Content
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name:  Create Nginx Reverse Proxy Configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf  
  notify: # how nginx will know that server has to be restarted
  - restart nginx 