- name: Setup SystemD {{component}} Service
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: demon-reload the service
  ansible.builtin.systemd:
    daemon_reload: true #here itself we can have enable and start also
    state: restarted
    name: "{{component}}"